### ISSUE TITLE
[critical] programming error - no return statement

### ISSUE THREAD

**Issue by Flippylosaurus** [nickvanw/ircx#21]
I tried to create a bot connecting IRC and telegram. I get the following error:
/usr/lib/go/src/pkg/github.com/nickvanw/ircx/bot.go:111: function ends without a return statement
Help would be appreciated.

**Comment by nickvanw** [comment]
Hi @Flippylosaurus! 

What version of Go are you running? You can find this out by typing `go version` at the terminal.
