### ISSUE TITLE
consider switching to sorcix/irc v2

### ISSUE THREAD

**Issue by mvdan** [nickvanw/ircx#26]
See https://github.com/sorcix/irc/tree/v2. Seems to have been in development over the past year.

Not sure how you would do that since it's hidden in a branch, however. Perhaps with dep.

**Comment by mvdan** [comment]
Update - definitely use vgo for this. sorcix/irc would need to add the pertinent go.mod file(s), though.

**Comment by nickvanw** [comment]
Closed in #32
